[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "pytellum_winterm_uw"
version = "1.0.1"
dependencies = [
    "PyJWT >= 2.12.1",
    "cryptography >= 47.0.0",
    "requests >= 2.33.1"
]
authors = [
    { name="Winter Miller", email="winterm@uw.edu" }
]
description = "A manager for interacting with Intellum's REST API"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/winterm-uw/pytellum"
Issues = "https://github.com/winterm-uw/pytellum/issues"